name: Docker Image CI

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

    steps:
      - uses: actions/checkout@v4
      - name: Login DockerHub

        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build the Docker image
        run: docker build -t cicd-pipeline:latest .

      - name: Tag the Docker image
        run: docker tag cicd-pipeline:latest $DOCKER_USERNAME/cicd-pipeline:latest

      - name: Push to DockerHub
        run: docker push $DOCKER_USERNAME/cicd-pipeline:latest
